version: '3.8'

services:
  project1-webapplication:
    build:
      context: .
      dockerfile: ./Dockerfile
#     target: build
    container_name: project1_webapp
    restart: always
#    command:
    depends_on:
      - project1-nginx
      - project1-postgres
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/healthcheck"]
      interval: 10s
      timeout: 3s
      retries: 3

  project1-nginx:
    images: nginx:1.25.3
    restart: always
    container_name: project1_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf

  project1-postgres:
    image: postgres:16
    container_name: project1_psql
    ports:
      - "5432:5432"
    env_file:
     - ./postgres.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  project1-mongodb:
    image: mongo:6.0.13
    container_name: project1_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
